KEYWORDS = ["include","Program", "if", "else", "elif", "for", "while", "func", "run", "class",]
BUILT_IN = ["echo","print", "input", "system"]
MATH = ["pow", "sqrt", "factorial", "complex", "sin", "cos", "tan", "integral"]
DATATYPE = ["var","bool", "int", "float", "str", "char"]
OPERATORS = ["+", "-", "*", "/", "**", "%", "//", "="]
COMARTION_OPERATORS = ["==", "!=", ">", "<", "<=", ">="]
INCREMENT_OPERATORS = ["+=", "-=", "*=", "/=", "**="]
LOGICAL_OPERATORS = ["&&", "||", "and", "or"]
